### ISSUE TITLE
Sad error message when attempting to use an undefined alias.

### ISSUE THREAD

**Issue by tpickett66** [daveadams/go-rapture#3]
I just tried to assume a role with an alias that wasn't defined and got an error message that was confusing at first.

```
ERROR: Could not assume role 'inst-por': InvalidParameter: 1 validation error(s) found.
- minimum field size of 20, AssumeRoleInput.RoleArn.
```

It would be nice to catch that this was an alias that wasn't defined and give an error indicating the problem. I may have some time to take a pass at fixing this tomorrow or Saturday.

**Comment by daveadams** [comment]
Fixed by #4 ! Thanks @tpickett66 !
